### ISSUE TITLE
Cannot build Fayde library - conflict with typescript base library

### ISSUE THREAD

**Issue by asthomas** [wsick/Fayde#101]
I cloned the Fayde project from Github, then issued:
```
npm install
bower update
grunt
```
I get many errors during the build like
```
>> D:/Projects/github/Fayde/node_modules/grunt-typescript/node_modules/typescript/bin/lib.d.ts(14228,5): error TS2300: Duplicate identifier 'clientX'.
>> D:/Projects/github/Fayde/node_modules/grunt-typescript/node_modules/typescript/bin/lib.d.ts(14229,5): error TS2300: Duplicate identifier 'clientY'.
>> D:/Projects/github/Fayde/node_modules/grunt-typescript/node_modules/typescript/bin/lib.d.ts(14230,5): error TS2300: Duplicate identifier 'identifier'.

>> src/Input/TouchInterfaces.ts(2,5): error TS2300: Duplicate identifier 'identifier'.
>> src/Input/TouchInterfaces.ts(6,5): error TS2300: Duplicate identifier 'clientX'.
>> src/Input/TouchInterfaces.ts(7,5): error TS2300: Duplicate identifier 'clientY'.
```

The problem is that both the lib.d.ts typescript library and the Fayde library define the same interfaces with overlapping members.

I suspect that I'm working with different versions of the tools from yours.  I run into little things with all of the projects from github, like missing casts or slight changes in the typescript compiler's expectations.  I update what I can, but I don't know how to manage this one.

**Comment by BSick7** [comment]
Which typescript version are you using to compile?

**Comment by BSick7** [comment]
This is definitely an issue compiling on `typescript 1.5.0-beta`.

**Comment by BSick7** [comment]
I have been polyfilling touch interfaces.  Typescript 1.5.0-beta introduced the same members.  Fixing shortly.

**Comment by asthomas** [comment]
This now compiles.  When I attempt to use it in my project, I get this error:
```
>> app/lib/fayde/dist/fayde.d.ts(3592,5): error TS2300: Duplicate identifier 'MSPOINTER_TYPE_MOUSE'.
```
The conflict is with a definition in typescript/bin/lib.d.ts.  lib.d.ts defines MSPOINTER_TYPE_MOUSE as a number, where fayde defines it as a string.

According to "npm list" my typescript version is 1.3.0.

**Comment by asthomas** [comment]
I just tried typescript 1.5.0-beta and it is working without problems.

**Comment by BSick7** [comment]
Based on this, they removed `MSPOINTER_TYPE_MOUSE` from `MSPointerEvent`.  I polyfilled it which will cause older tsc versions to break.

https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-15

I may remove it and find a better way to use in code.
