### ISSUE TITLE
Fayde project scaffolding issues

### ISSUE THREAD

**Issue by Sally-Xu** [wsick/Fayde#108]
1) After creating a fayde project with "yo fayde" and run Gruntfile typescript build, I got the following error:

Running "typescript:build" (typescript) task
>> BasePath option has been deprecated. Method for determining an output directory has been changed in the same way as the TSC. Please re-set output directory with the new rootDir option or use keepDirectoryHierachy option. However, keepDirectoryHierachy option would not be available long.

 I had to remove the "basePath: dirs.app" entry from the typescript build option in order to run the typescript build.

2) When I try to run the default.html, I got a blank page with "Uncaught Error: ./fayde.json HTTP status: 404".  How do I generate fayde.json?

**Comment by BSick7** [comment]
For 1: `grunt-typescript` introduced some incompabilities that I am updating now.
For 2: `npm install -g fayde-unify`. When you run `bower install`, unify will update your fayde.json file.

**Comment by BSick7** [comment]
Fixed, run `npm install -g generator-fayde` to update.

**Comment by BSick7** [comment]
Run `npm install -g generator-fayde-library` if you are looking to get fixes for generating libraries.
