### ISSUE TITLE
Conversion from string to multi-numeric types should accept space as a separator

### ISSUE THREAD

**Issue by asthomas** [wsick/Fayde#113]
String values for Point, Thickness, etc. can be specified as "10,10" or "10 10" in Silverlight.  Fayde accepts comma, but not space.

**Comment by BSick7** [comment]
Fixed with pull request merge 2d64420710fa1d9b3d1571d464490181b14fadac.

**Comment by BSick7** [comment]
Reopening after finding issue with this merge request.

**Comment by BSick7** [comment]
Fixed in commit 8f19c10e9dbe225e3686e8656b40afc18ee8655a.

**Comment by asthomas** [comment]
I think that splitCommaList could be reduced to:
```
str.split(/ *[, ] */);
```
The regex could be made static for speed.

**Comment by BSick7** [comment]
In this example, the regex was 4x slower:
http://jsperf.com/split-join-vs-regex-replace

**Comment by asthomas** [comment]
That's not a representative test.  Try this one:
http://jsperf.com/string-split-join-split-vs-regex

In Chrome the regex performs much better.  In Firefox, the regex is a little bit better.
