### ISSUE TITLE
How to define namespace prefix for controls?

### ISSUE THREAD

**Issue by Sally-Xu** [wsick/Fayde#122]
If a control is under Fayde.Controls namespace in the Fayde.Controls library, we define the namespace prefix for that control as
        xmlns:controls="lib://fayde.controls"

But how do I define the namespace prefix for a control which is within the same library but under different namespace (say a control is under namespace of Fayde.Controls.Primitives)? I've tried the following and it didn't work:
        xmlns:primitives="lib://fayde.controls.primitives"

**Comment by BSick7** [comment]
Try `xmlns:primitives="lib://fayde.controls/Primitives"`

**Comment by Sally-Xu** [comment]
ya, that works.

**Comment by BSick7** [comment]
Added wiki article https://github.com/wsick/Fayde/wiki/Namespace-Declarations
