### ISSUE TITLE
Set Binding Source using ElementName doesn't work in Item Template.

### ISSUE THREAD

**Issue by Sally-Xu** [wsick/Fayde#128]
I'm trying to set binding in ContextMenu's ItemTemplate.  Here is the testing XAML:

<TextBlock Grid.Row="1" MouseLeftButtonDown="{EventBinding Command={Binding Path=DataContext.MenuClickCmd, ElementName=Root, CommandParameter={Binding}}}" 
Text="Test" />

    <Border Grid.Row="2" Background="Black" Padding="5" HorizontalAlignment="Center" VerticalAlignment="Center" x:Name="Root">
      <TextBlock Foreground="White" Text="Right click me!">
        <controls:ContextMenuService.ContextMenu>
          <controls:ContextMenu ItemsSource="{Binding Menu}">
            <controls:ContextMenu.ItemTemplate>
              <DataTemplate>
                <Grid>     
                  <TextBlock MouseLeftButtonDown="{EventBinding Command={Binding Path=DataContext.MenuClickCmd, ElementName=Root, CommandParameter={Binding}}}" Text="{Binding Header}" />
                </Grid>
              </DataTemplate>
            </controls:ContextMenu.ItemTemplate>           
          </controls:ContextMenu>
        </controls:ContextMenuService.ContextMenu>
      </TextBlock>
    </Border>

The TextBlock outside of the ContextMenu's ItemTemplate works fine. But the one inside the ItemTemplate can't find the "Root" Element set in the ElementName binding field. I'm getting "[EVENTBINDING]: Could not find command target for event 'MouseLeftButtonDown'." error  at EventBindingExpression.ts:80 .

**Comment by Sally-Xu** [comment]
Instead of using ElementName=XXX, using RelativeSource = {RelativeSource ItemsControlParent} is working.  

This one works:
<DataTemplate>
<TextBlock MouseLeftButtonDown="{EventBinding Command={Binding Path=DataContext.MenuClickCmd, RelativeSource={RelativeSource ItemsControlParent}}, CommandParameter={Binding}}}" Text="{Binding Header}" />
</DateTemplate>

**Comment by BSick7** [comment]
This doesn't work in Silverlight either.

**Comment by Sally-Xu** [comment]
If I remember correctly, that was how it works in Silverlight (by using ElementName). I don't think Silverlight/WPF even has ItemsControlParent in RelativeSource.  But I like ItemsControlParent, just need to be documented it if that's how it supposed to work.

**Comment by BSick7** [comment]
I tried the example in Silverlight and it doesn't work.  Binding cannot find the specified ElementName because it belongs to a different logical tree.  To be able to do this would require attaching the ContextMenu to the parent logical tree; however, this introduces other problems.

**Comment by Sally-Xu** [comment]
Just tried to set RelativeSource with AncestorType=ItemsControl 

RelativeSource={RelativeSource AncestorType=ItemsControl} => This doesn't work either.  

The only way to make it work is to set RelativeSource={RelativeSource ItemsControlParent}

**Comment by BSick7** [comment]
Fayde requires `Mode=FindAncestor` to be explicitly set.
Opened new issue #139 to track.
