### ISSUE TITLE
DateTime.toString("Y")  not consistent with C#

### ISSUE THREAD

**Issue by Sally-Xu** [wsick/Fayde#132]
When using "Y" format, DateTime.toString("Y") returns "Month, Year".

Silverlight or C# in general returns "Month Year" (without comma).

**Comment by BSick7** [comment]
I get this from Fayde which is identical to Silverlight.

Fayde
![screenshot](https://cloud.githubusercontent.com/assets/830878/8260776/c6f11042-1693-11e5-95b5-9904e1478b23.png)

Silverlight
![screenshot2](https://cloud.githubusercontent.com/assets/830878/8260803/ee2f48d6-1693-11e5-9169-2af21544fde6.png)

**Comment by Sally-Xu** [comment]
This is what I got from Silverlight:
![sl](https://cloud.githubusercontent.com/assets/1042478/8261296/4816dd20-1697-11e5-87a9-02ef27c9bdf1.png)

**Comment by BSick7** [comment]
Which version of silverlight

**Comment by Sally-Xu** [comment]
I'm on Silverlight 5. I've also tested in non Silverlight project (like a simple C# UnitTest project). Both return without comma.

**Comment by Sally-Xu** [comment]
Do you see the comma in your windows' calendar header bar?

**Comment by BSick7** [comment]
Ooh.  You could be using a different culture.  What are your culture settings?

**Comment by Sally-Xu** [comment]
default US.

**Comment by BSick7** [comment]
Based on msdn: https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#YearMonth.

**Comment by Sally-Xu** [comment]
Now I think difference is between Win8 and Win7. Are you on windows 7? The calendar (or the same silverlight code) on my windows 7 machine output "June, 2015".

**Comment by BSick7** [comment]
I am going to close this for now.  As of now, the code is consistent with MSDN.  We also don't want to be held hostage by .NET.  Replicating .NET environmental differences is caustic to future development.
