### ISSUE TITLE
DateTime.Today gives wrong date 

### ISSUE THREAD

**Issue by Sally-Xu** [wsick/Fayde#134]
My current local time is 6/20/2015 10PM,  Here is Fayde's DateTime.Today's output in the debug watch window:

Date: DateTime
Day: 21
DayOfWeek: 0
DayOfYear: 170
Hour: 0
Kind: 2
Millisecond: 0
Minute: 0
Month: 6
Second: 0
Ticks: 1434844800000
TimeOfDay: (...)
Year: (...)
_InternalDate: Sat Jun 20 2015 20:00:00 GMT-0400 (US Eastern Daylight Time)

Notice the Day is 21 instead of 20. 

Shouldn't the default Kind be Local instead of UTC?

**Comment by BSick7** [comment]
Fixed in 0.16.39.

**Comment by Sally-Xu** [comment]
The fix only fixed DateTime.Today.  But there is new problem. 

If I create a date with the following code:

var d = new DateTime(2015, 6, 29)  // this is today's date, so it should be the same as d.Date

I tried to  compare the dates using Datetime.Compare and got the following result:
 
DateTime.Compare(d.Date, d) ! = 0   // this is not expected

or 

DateTime.Compare(d.Date, DateTime.Today) ! = 0

**Comment by BSick7** [comment]
From the latest build, this is what I get in Chrome.

![screen](https://cloud.githubusercontent.com/assets/830878/8422327/f5e9caf8-1ea7-11e5-8e41-14ac99ee1454.png)

**Comment by Sally-Xu** [comment]
Did you try DateTime.Compare(new DateTime(2015, 6, 29).Date,  DateTime.Today)

**Comment by BSick7** [comment]
Updated comment.

**Comment by Sally-Xu** [comment]
Strange, now I try it, got the same result as yours. But I definitely saw different result when I first updated Fayde library this evening. never mind then.
