### ISSUE TITLE
Check box control in popup

### ISSUE THREAD

**Issue by deepaksm1** [wsick/Fayde#138]
I have added multiple CheckBoxes inside popup. If I close and reopen popup then tick mark is not appearing on checkboxes which are checked previously. But as per my observation these checkboxes are in checked state internally. Only it doesn't show tick mark visually.

**Comment by BSick7** [comment]
I am using a ComboBox to simulate a popup.  When I close the popup, the popup visual tree is detached.  As a result, all storyboards are stopped.  This appears to be proper behavior; however, the storyboard should restart upon reattaching.

**Comment by BSick7** [comment]
Fixed in v0.16.38.
