### ISSUE TITLE
DateTime value set in XMAL doesn't get converted to DateTime after the XAML is Loaded

### ISSUE THREAD

**Issue by Sally-Xu** [wsick/Fayde#144]
Sample XAML:
<controls:DatePicker SelectedDate="07/03/2015" />

The SelectedDate is still a string type after the control is loaded. It should be in DateTime type.

**Comment by BSick7** [comment]
Please submit a PR with a reproducible test.

**Comment by Sally-Xu** [comment]
I found the reason for this:  there is no converter for DateTime type in the nullstone.convertAnyToType function, only a converter for Date type. 

 export function convertAnyToType (val: any, type: Function): any {
        var converter: (val: any) => any = (<any>converters)[<any>type];
        if (converter)
            return converter(val);
        if (type instanceof Enum) {
            var enumo = (<Enum><any>type).Object;
            if (enumo.Converter)
                return enumo.Converter(val);
            val = val || 0;
            if (typeof val === "string")
                return enumo[val];
            return val;
        }
        return val;
    }
    
Not sure how to fix this because DateTime is defined in Fayde, nullstone certainly doesn't know this type.

**Comment by BSick7** [comment]
Converters can be registered through `nullstone.registerTypeConverter(<type>, <converter>)`.
Implemented in v0.16.42.
