### ISSUE TITLE
HyperLinkButton Error when no TargetName is set

### ISSUE THREAD

**Issue by Sally-Xu** [wsick/Fayde#146]
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined at line 19

 switch (targetName.toLowerCase()) 

Need set Default Value for TargetName to "_self" in the TargetNameProperty:

static TargetNameProperty = DependencyProperty.Register("TargetName", () => String, HyperlinkButton, "_self");

**Comment by BSick7** [comment]
Fixed in v0.16.43.
