### ISSUE TITLE
Memory leak in TextBox

### ISSUE THREAD

**Issue by asthomas** [wsick/Fayde#149]
When the content of a TextBox changes, the previous content is added to the TextProxy.$$undo member.  There is no upper bound on the size of the $$undo array, so a long-lived TextBox that encounters many changes will grow memory forever.

In some cases, undo behaviour is not necessary.  It would be nice to be able to explicitly disable undo tracking on the TextBox, or limit it to a single prior value to allow the user to press escape while editing the value.

**Comment by BSick7** [comment]
This is definitely an unintended bug.  There is a max history size that is being ignored.

**Comment by BSick7** [comment]
Fixing in `textbox-history-limit` branch.  Still need to add tests before merging into `master`.

**Comment by BSick7** [comment]
Fixed in v0.16.44.

**Comment by BSick7** [comment]
Added "undo disable" as enhancement #151
