### ISSUE TITLE
DateTime.AddDays/AddHours sometimes gives wrong date

### ISSUE THREAD

**Issue by Sally-Xu** [wsick/Fayde#152]
Here is the test case:

            var day = new DateTime(2015, 11, 1);          
            console.log(day.toString());          // output: 2015-11-01T00:00:00  --correct
            console.log(day.AddDays(1).toString());  //output: 2015-11-01T23:00:00 -- NOT correct
            console.log(day.AddDays(2).toString());  //output: 2015-11-02T23:00:00 -- NOT correct
            console.log(day.AddHours(24).toString()); //output: 2015-11-01T23:00:00--NOT correct
            console.log(day.AddMonths(1).toString()); //2015-12-01T00:00:00--correct

**Comment by Sally-Xu** [comment]
I think it happens on all the DST start and end date.

**Comment by BSick7** [comment]
Fixed in v0.16.45.
