### ISSUE TITLE
How can achieve File Upload functionality in fayde?

### ISSUE THREAD

**Issue by deepaksm1** [wsick/Fayde#164]
How can achieve File Upload functionality in fayde?

**Comment by BSick7** [comment]
This has not been implemented.  Feel free to build one in a new repo and we can guide development.

**Comment by BSick7** [comment]
Please look at our new library [fayde.io](https://github.com/wsick/fayde.io) for upload functionality.  It is currently in an alpha phase, so we need some heavy testing and feedback.
