### ISSUE TITLE
Datepicker issue after updating Fayde new version

### ISSUE THREAD

**Issue by deepaksm1** [wsick/Fayde#166]
Recently we have updated fayde version. After updating this we are getting issues in pages where datepicker control is used. 

```
 <controls:DatePicker SelectedDate="{Binding FromDate, Mode=TwoWay}"  Margin="5,0">
        </controls:DatePicker>
```

Error in browser: Cannot parse DateTime value 'undefined'

We get this error if SelectedDate Binding is there

**Comment by BSick7** [comment]
Moved to https://github.com/wsick/Fayde.Controls/issues/11
