### ISSUE TITLE
How to show bytes data as a source for Image in fayde?

### ISSUE THREAD

**Issue by deepaksm1** [wsick/Fayde#168]
How to show bytes data as a source for Image in fayde?

**Comment by BSick7** [comment]
What data structure is the data in the browser?

**Comment by BSick7** [comment]
In Fayde v0.16.53, `BitmapImage.SetSource` has been implemented.  

In addition, `Image.Source` and `ImageBrush.ImageSource` will coerce `ArrayBuffer` into a `BitmapImage` by utilizing `SetSource`.

A raw example is seen in the testsite.

View:
https://github.com/wsick/Fayde/blob/master/testsite/Media/image-setsource.fap

ViewModel:
https://github.com/wsick/Fayde/blob/master/testsite/Media/ImageSetSourceViewModel.ts
