### ISSUE TITLE
MultiBinding

### ISSUE THREAD

**Issue by JigsSodvadiya** [wsick/Fayde#187]
Hi,

This is Jignesh.

How to implement MultiBinding in Fayde.

Giving this Kind of Error:
Could not resolve type [http://schemas.wsick.com/fayde][MultiBinding].

Thanks,
Jignesh

**Comment by BSick7** [comment]
I have not looked into the details of how MultiBinding works.  In much the same way that Binding tracks changes to its source using (PropertyPathWalker)[https://github.com/wsick/Fayde/blob/master/src/Data/Property/PropertyPathWalker.ts], I'm guessing MultiBinding would have a set of trackers representing each binding.

**Comment by JigsSodvadiya** [comment]
Thanks Dear,

I see this link. Can you give me small example to work with PropertyPathWalker.

Thanks,
Jignesh
