### ISSUE TITLE
Tooltip content not showing in second time

### ISSUE THREAD

**Issue by DheerajSaravagi** [wsick/Fayde#204]
Tool tip content is showing first time when we enter mouse again it is not showing content
```
      <Border Background="Transparent" ToolTipService.ToolTip ="THIS IS TEST TOOLTIP">
        <TextBlock Margin="5,0" Text="test" />
      </Border>
```

**Comment by dp901** [comment]
I solved this issue by adding a second VisualTransition in my theme.xml file where tooltip style is defined. There was a single VisualTransition, from: Open -> to: Closed. I think there has to be a second transition, from: Closed -> to: Open.
