### ISSUE TITLE
HyperlinkButton TargetName _Blank not working in IE11

### ISSUE THREAD

**Issue by deepaksm1** [wsick/Fayde#206]
HyperlinkButton TargetName = _Blank not working in IE11 Version 11.0.9600. Page should open in new window if target is _Blank. 

```
<HyperlinkButton Content="Download" Foreground="Teal" NavigateUri="{Binding Path=FileId, Converter={StaticResource DocumentLinkConverter}}" TargetName="_Blank" />
```

**Comment by deepaksm1** [comment]
It works if I change launchDummyLink function in fayde.js as below:
```
function launchDummyLink(target, navigateUri) {
            dummyLink = dummyLink || document.createElement('a');
            dummyLink.style.position = "absolute";
            dummyLink.style.left = "-100px";
            dummyLink.style.top = "-100px";
            dummyLink.href = navigateUri;
            dummyLink.target = target;
            document.body.appendChild(dummyLink);
            dummyLink.click();
            document.body.removeChild(dummyLink);
       }
```

**Comment by deepaksm1** [comment]
Fayde version: 0.19.7

**Comment by BSick7** [comment]
Just tested in IE 11, Edge, and Chrome. All working as intended.

**Comment by BSick7** [comment]
```xaml
<HyperlinkButton Content="Download" Foreground="Teal" NavigateUri="/Home" TargetName="_Blank" />
```

Before clicking:
![image](https://cloud.githubusercontent.com/assets/830878/13321890/bd999fb0-db9f-11e5-97c9-664657d0a428.png)

After clicking:
![image](https://cloud.githubusercontent.com/assets/830878/13321880/b1dad158-db9f-11e5-86e2-d6d3daa9dde8.png)

**Comment by deepaksm1** [comment]
Why this is not working when we are checking, I checked this on 4 to 5 PCs in our office. But no luck. Is there any settings in IE?
