### ISSUE TITLE
Console Error on EventBinding

### ISSUE THREAD

**Issue by JigsSodvadiya** [wsick/Fayde#216]
TabControl and ComboBox giving Console Error when I am using EventBinding with SelectionChange event.

**Comment by BSick7** [comment]
Please provide the error message and context.

**Comment by JigsSodvadiya** [comment]
Thanks for Reply

Message = [EVENTBINDING]: Could not find command target for event 'SelectionChanged'.

XAML:
<ComboBox ItemsSource="{Binding Path=StatesResult}"
                        Width="200"
                        Height="36"
                        DisplayMemberPath="Description"
                        SelectedValuePath="Description"
                        SelectedItem="{Binding Path=SelectedState, Mode=TwoWay}"
                        SelectionChanged ="{EventBinding cmbSelectedItem}"   />


While I am going or coming Back from this Page than giving error over console.

**Comment by BSick7** [comment]
`cmbSelectedItem` looks like the name of another xaml element.
`EventBinding` expects a Command which can either be an `ICommand` or a function.

**Comment by BSick7** [comment]
Take a look at the following 2 files to see usage.

https://github.com/wsick/Fayde/blob/master/testsite/Binding/eventbinding.fap
https://github.com/wsick/Fayde/blob/master/testsite/Binding/TestViewModel.ts
