### ISSUE TITLE
Image from cached memory

### ISSUE THREAD

**Issue by JigsSodvadiya** [wsick/Fayde#226]
Hi,

We are using some images frequently. So Is it possible one first time download from server another time no need to download.

**Comment by BSick7** [comment]
Are you wanting to do a download of all images upon initialization or load the images on-demand?

**Comment by JigsSodvadiya** [comment]
I want to load image on-demand once than after access that image from cached memory.

**Comment by BSick7** [comment]
Your browser should handle that for you.

**Comment by JigsSodvadiya** [comment]
Can I Know, what thing I have to configure in Browser.

**Comment by BSick7** [comment]
By default, the browser will cache images based on the full request path.
I usually have chrome devtools to force a cache refresh.  Make sure yours isn't set up for that.

**Comment by BSick7** [comment]
This seems resolved. Closing.
