### ISSUE TITLE
TreeView Control Getting Error On Re-Feed 

### ISSUE THREAD

**Issue by JigsSodvadiya** [wsick/Fayde#228]
Hi,

I am using TreeView. I bind a Collection with Itemsource. On first time I feed thatCollection and working fine but when I re-feed that collection than Treeview give's below error.

![treeview bug](https://cloud.githubusercontent.com/assets/15010124/12108128/c513b25e-b399-11e5-8fca-4a65c691f65e.png)

----------------------TreeView.ts >>  CheckForSelectedDescendents (item: TreeViewItem)

Unable to get property 'getEnumerator' of undefined or null reference

**Comment by JigsSodvadiya** [comment]
In both case getting error:
1) Collection clear on rebind.
2) Collection declare new on rebind.

**Comment by BSick7** [comment]
What is `CriteriaItem`?  I need some context on how it is being used as a container.
Does that inherit from `TreeViewItem`?

**Comment by JigsSodvadiya** [comment]
Hi,

CriteriaItem Is a ViewModel Class and that class not inherit with TreeViewItem. Not ViewModel if we use normal Class Collection than this problem occur.

**Comment by BSick7** [comment]
CriteriaItem being a container looks suspicious.  What does your view xaml look like?

**Comment by deepaksm1** [comment]
When we binding multi level collection (more than one level) in treeview, and after that if we clear collection or rebind another collection then treeview throws these error.

**Comment by JigsSodvadiya** [comment]
Hi,

Sample of Source code has been available on below link:
https://www.dropbox.com/s/5gwcxtzza04qe0q/TreeViewIssue.rar?dl=0

First Time TreeView Load but on another time application crash.
