### ISSUE TITLE
Console error displayed in IE but not in Chrome

### ISSUE THREAD

**Issue by mikefills** [wsick/Fayde#236]
I could only see this in IE, but not in Chrome:

![snip_20160202104835](https://cloud.githubusercontent.com/assets/15019084/12746492/9a9edba6-c9a7-11e5-9dbc-37e851bda7b9.jpg)

In order to get an error use something invalid in the XAML:

`<Button><Button>`

**Comment by mikefills** [comment]
OK, now I see that DOMParser doesn't throw any error. Instead, it returns a document with <parseerror> node
http://stackoverflow.com/questions/11563554/how-do-i-detect-xml-parsing-errors-when-using-javascripts-domparser-in-a-cross
https://developer.mozilla.org/en-US/docs/Web/API/DOMParser#Parsing_XML
https://github.com/cburgmer/sane-domparser-error

**Comment by BSick7** [comment]
Added error reporting in 0.19.14.
