### ISSUE TITLE
Change Line Color in Chart "Fayde.DataVis"

### ISSUE THREAD

**Issue by JigsSodvadiya** [wsick/Fayde#241]
Hi,

1) How we can change line Color in Change  "Fayde.DataVis".
2) Is it possible to Binding Minimun and Maximum Property. Source Code Below
--------------------------------
 <dv:CartesianChart.YAxis>
            <dv:LinearAxis Minimum="0" Maximum="100" />
   </dv:CartesianChart.YAxis>
-----------------------------------------------------------

**Comment by BSick7** [comment]
Please log issues against the correct repo. Fayde.DataVis is also experimental at this time.

**Comment by BSick7** [comment]
Every Series (the base of LineSeries) has a SeriesPresenter (LineSeriesPresenter).  The LineSeriesPresenter allows you to set the LineStyle.

**Comment by JigsSodvadiya** [comment]
Hi,
Thanks Dear.
When I set Style Globally than it work but when I set style to particular series than Fayde crash.
::Style Code are Below::
`   <Style x:Key="LineSeries_QuotePrice" TargetType="dv:LineSeriesPresenter">
      <Setter Property="LineStyle">
        <Setter.Value>
          <Style TargetType="Polyline">
            <Setter Property="Stroke" Value="Red" />
            <Setter Property="StrokeThickness" Value="1" />
          </Style>
        </Setter.Value>
      </Setter>
    </Style>`

:: Code for Line Series::
`  <dv:LineSeries ItemsSource="{Binding ProductBid_ChartData}" IndependentValuePath="Category" DependentValuePath="Value_LivePrice">
              <dv:LineSeriesPresenter LineStyle="{StaticResource LineSeries_QuotePrice}"/>
            </dv:LineSeries>`

Please guide me.

**Comment by BSick7** [comment]
You are setting the `LineStyle` to the a style for `LineSeriesPresenter`.
You should either set the LineStyle to a style targetting Polyline or embed the style in the line series code.

**Comment by JigsSodvadiya** [comment]
Hi dear, 

Can you provide small code for LineStyle in Chart?

**Comment by BSick7** [comment]
Moving to https://github.com/wsick/Fayde.DataVis/issues/1
