### ISSUE TITLE
Listbox Scrollbar issue

### ISSUE THREAD

**Issue by Ronmenator** [wsick/Fayde#247]
Hi,

Attached is an example of a Listbox scrollbar problem.

You have a page with two Columns. 

In the left Column, you have a Listbox that has a list of objects. Each object has a list of children.
In the right Column, you have another Listbox whose ItemsSource is bound to the first Listbox's SelectedItem.Children.

As you swap between the Items in the Left Column Listbox, the right Column Listbox displays the children of the Selected item.

The problem arises when one of the elements on the left has a large number of children so that a scrollbar is visible on the Right Listbox. Swapping back to an item that does not require a Scrollbar on the right causes the ListBox to get a scrollbar that is massive and scrolled down to the bottom.

See the attached code. I am not close to something to generate a pull request with.

[ListBoxScroll.zip](https://github.com/wsick/Fayde/files/137094/ListBoxScroll.zip)

**Comment by BSick7** [comment]
I believe this is intended by the authors of the metro theme.
They gave the scrollbars height/width of 18; however, the visuals never takes up 18px.

**Comment by BSick7** [comment]
I'm going to close this, but if you feel strongly about changing the theme, we can reopen.

**Comment by Ronmenator** [comment]
Ok, to solve the scrolling to the bottom issue, I just have to remove the width and height of the scrollbar.

**Comment by BSick7** [comment]
I misunderstood the issue.  Reopening.
