### ISSUE TITLE
HyperlinkButton Navigate code is broken in the latest build when targetName is set to a Frame

### ISSUE THREAD

**Issue by Sally-Xu** [wsick/Fayde#52]
I use HyperlinkButton inside my TreeView Item Template. The TargetName is set to "ContentFrame" which is a Frame on the page.  When the button is clicked, it should display the page which the URL pointing to in the Frame, which was working before version 0.9.8.18.  Now it is broken. I debugged code and found the problem is in the HyperlinkButton._Navigate function, the following code no longer finds the Frame on the page. 

var targetUie = this.FindName(targetName);

**Comment by BSick7** [comment]
I found the deeper issue with finding the target for navigation.  Fix will be included with implementation of `TargetName` for issue #143.

**Comment by BSick7** [comment]
Fixed in Fayde v0.16.41.
