### ISSUE TITLE
TextBlock TextWrapping not updating on resize

### ISSUE THREAD

**Issue by Ronmenator** [wsick/Fayde#83]
TextBlock does not update it's own layout on resize when TextWrapping is set to Wrap

**Comment by BSick7** [comment]
Can you send either repro steps or send a pull request with a testsite example?

**Comment by Ronmenator** [comment]
1. Add a TextBlock to a page - make sure the text wraps at least once.
2. Resize the browser

The text do not unwrap or wrap unless you refresh the browser page.
