### ISSUE TITLE
Tab function not working in IE

### ISSUE THREAD

**Issue by Ronmenator** [wsick/Fayde#88]
FYI. Raising the issue so that we can keep track of it.

I could not get the pull request to pick up the changes.

Attached is the changes in zip format.

Regards

Ronnie

From: Fayde Project [mailto:fayde.project@gmail.com] 
Sent: Thursday, January 29, 2015 1:15 PM
To: Ronnie Barnard
Subject: Re: Tab function not working in IE

Can you build a reproduction in Fayde repo under testsite and send a pull request?
Brad

On Thu, Jan 29, 2015, 13:48 Ronnie Barnard <ronnieb@iprolive.com> wrote:
Hi,
 
The tab function is not working in IE. Are you aware of this one?
 
Regards,

**Comment by Ronmenator** [comment]
I emailed the test zip to Brad

**Comment by BSick7** [comment]
After looking at the test, I'm not sure the issue.  When I press tab, it switches between the 2 text boxes.
@Ronmenator Can you elaborate?

**Comment by Ronmenator** [comment]
I am running IE 11.0.9600.17631 on Windows 8.1. When I press tab the navigation jumps to the URL and back to the first control in the list.

I can replicate the issue on browser stack with the settings as above.

**Comment by BSick7** [comment]
Thanks for the details. This looks specific to IE keyboard interop.
