### ISSUE TITLE
IE9 perfomrance timing stoping Fayde from working

### ISSUE THREAD

**Issue by Ronmenator** [wsick/Fayde#89]
This image shows the activePhaseTiming getting in the way of allowing Fayde to work on IE9, Windows 7.

![image](https://cloud.githubusercontent.com/assets/6628234/6332407/01adc79e-bb3a-11e4-8e98-4ed985bade41.png)

**Comment by BSick7** [comment]
What version are you using?  The performance APIs were forked over to https://github.com/wsick/perfex.  To utilize this new API, you have to manually add a script include for perfex.

**Comment by Ronmenator** [comment]
I upgraded it this morning to 0.6.18

**Comment by Ronmenator** [comment]
Never mind. Now it works. It could have been cache, but I don't think on browser stack they cache it.
