### ISSUE TITLE
generator-fayde-library spawnCommand error

### ISSUE THREAD

**Issue by asthomas** [wsick/Fayde#91]
In the file generator-fayde-library/generators/app/index.js, there is a call to
this.spawnCommand('npm install -g fayde-unify');
This fails in cygwin.  It should be:
this.spawnCommand('npm',['install', '-g', 'fayde-unify']);

**Comment by BSick7** [comment]
Fixed in v0.6.10 @ https://github.com/wsick/generator-fayde-library/commit/bdd6b7c53e7cd75b1c331ee5322aa55e5f7828b8.
