### ISSUE TITLE
ViewBox not implemented

### ISSUE THREAD

**Issue by asthomas** [wsick/Fayde#93]
We make extensive use of ViewBox for one or our projects.  It allows us to scale objects that are drawn as polygons.  Do you plan to implement it?

**Comment by BSick7** [comment]
There are no current intentions to implement.  This would be best suited for the https://github.com/wsick/fayde.controls repository.  Feel free to implement and send a pull request.

**Comment by asthomas** [comment]
I have started an implementation, but have run into a question I cannot figure out from the code.  I have created a Viewbox layout updater, measure pipe and arrange pipe.  I have a IViewboxUpdaterAssets that defines two properties, scaleX and scaleY.  I can see that my assets object is being passed as Input to my measure and arrange overrides.  I can see that scaleX and scaleY have their default values.

However, I don't see anywhere in the code sequence where I can set the scaleX and scaleY assets from the Viewbox control instance.  How do I provide values for the assets before the measure override is called?

**Comment by asthomas** [comment]
Upon further reflection, I think I need either the Viewbox object itself, or the ScaleTransform in the Viewbox's RenderTransform property while in the measure and arrange override functions.  I have to be able to adjust the RenderTransform in response to an arrange event.

**Comment by BSick7** [comment]
In this example, https://github.com/wsick/minerva/blob/master/src/controls/border/BorderUpdater.ts#L18-L21, we are initializing the asset values to defaults.  Each `Updater` is attached to every `UIElement` node.

Generally speaking, reactions are propagated through the `Updater` by perturbing `Updater` assets that will cause changes in the next layout/render pass.

@ https://github.com/wsick/Fayde/blob/master/src/Core/UIElement.ts#L338, this is a reaction to `UIElement.RenderTransform`.  If members of `Transform` change, this reaction will also fire.

**Comment by BSick7** [comment]
I missed something in the previous comment.  To get at the Updater:
```
var border = new Border();
var updater = border.XamlNode.Updater;
```

**Comment by BSick7** [comment]
If you're modifying `RenderTransform`, you may not need a measure pipe or arrange pipe at all.

**Comment by asthomas** [comment]
If I only modify the RenderTransform without modifying the state.arrangedSize then I think that other controls will not know the visual size of the contained child of the ViewBox, so things like Grid auto row and column sizing will be wrong.

**Comment by BSick7** [comment]
Correct me if I'm wrong, but a `ViewBox` would be modifying the `RenderTransform` of the containing visual.  Given this is the case, the `ViewBox` and containing visual would need some predefined Width/Height.

**Comment by BSick7** [comment]
In other words, a ViewBox will automatically lay out to its container; whereas, the child visual should set a size.  The ViewBox will stretch the child visual to the ViewBox constraints.

**Comment by asthomas** [comment]
I realized that didn't make sense as soon as I wrote it.  However, I do think there's a valid reason to play with the measure and arrange...
A Viewbox does not modify the child's RenderTransform.  It can't, since the child could have a RenderTransform for its own reasons.  So the Viewbox modifies its own RenderTransform based on its available size and the desired size of the child.  In order to know the child's desired size, it asks the child to measure with an infinite available size.  It then gives this ideal desired size back to the child as its available size and sets its own (the Viewbox's) render transform to compensate for the difference between the child's perceived available size and the true available size (the available size for the Viewbox).
This strategy does two things:  1) it allows the child to render at its ideal size, and 2) it avoids the need for the child or the XAML designer to set a reference size to use when computing the scaling factor.
I think the best time to do this is during the measure and arrange.  If the Viewbox waits until the child has already measured and arranged, the child will have already been laid out in the actual available size for the Viewbox, which could produce a non-ideal layout.  The Viewbox would then scale that layout.

**Comment by BSick7** [comment]
Good thoughts.  You are right about the RenderTransform.  You shouldn't modify your child's RenderTransform.  

At a minimum, you will need to hook into the ProcessDown pipeline (described @ https://github.com/wsick/minerva/blob/master/docs/engine.md).  Ultimately, you are going to affect the ViewBox-Updater's `absoluteXform`.  As the name suggests, this pipeline is processed running down the tree.  This transform will propagate to children.

**Comment by BSick7** [comment]
The base ProcessDown pipeline tapins are enumerated @ https://github.com/wsick/minerva/blob/master/src/core/processdown/ProcessDownPipeDef.ts#L46-L54.

**Comment by BSick7** [comment]
After looking at the decompiled WPF code, it looks like they wrap the Child visual with an auto-generated visual.  During measure, they give infinite size in MeasureOverride (as you said).  They use the returned dimensions to compute scale factors and return its own size based on those 2 dimensions.  The internal transform is applied to the auto-generated visual during arrange after calculating scaling metrics.

**Comment by asthomas** [comment]
That would be better.  Then the RenderTransform of the Viewbox would be available to the user - he might want to flip or rotate the Viewbox.
I don't know how to create that auto-generated visual and still get the XAML syntax correct.  What would my Viewbox need to extend and how would I create the auto-child so that the explicit child is still specified in XAML like this:
<Viewbox>
   <Button Content="Push Me"/>
</Viewbox>

**Comment by BSick7** [comment]
From msdn: "You typically use a Viewbox for 2D graphic images. You typically do not use a Viewbox for ordinary controls."  If you wanted to stretch a Button, you wouldn't need a ViewBox.

**Comment by BSick7** [comment]
Conceptually, creating an auto-generated visual is very easy to manage, but adds overhead.

I think it would be better to create a measure, arrange, and processdown pipe.  Your arrange pipe will affect `viewBoxXform` in your output (gets put back on assets).  Your processdown pipe would use `viewBoxXform` to apply to `absoluteXform` immediately before `processXform` tapin.

**Comment by asthomas** [comment]
I also saw that part about using a viewbox for images.  In reality, it's a really convenient way to stretch a geometry based on a Path.  It's also a good way to zoom a containers full of other controls.  The choice is to implement scaling manually on a resize event, which is of course possible, but why when Viewbox handles it automatically?

**Comment by asthomas** [comment]
I'm trying to implement the processdown pipe.  I've added my own ViewboxProcessDownPipeDef:
```javascript
	    this.addTapinBefore('processXform', 'preProcessXform',
				ViewboxLayoutUpdater.ProcessDownXformOverride);
```
In my ProcessDownXformOverride method I do this:
```javascript
		var xform = output.absoluteXform;
		mat3.multiply(xform, assets.viewbox.ScaleTransform.Value._Raw);
```
This is definitely executing, and definitely changes absoluteXform, but it appears to have no effect on the rendering.  How should I be modifying absoluteXform?

**Comment by BSick7** [comment]
Implemented in fayde.controls v0.17.4.
