### ISSUE TITLE
Wrap panel is not appearing on page.

### ISSUE THREAD

**Issue by deepaksm1** [wsick/Fayde#95]
Please guide how I can use wrap panel. I tried WrapPanel tag and controls:WrapPanel

**Comment by BSick7** [comment]
`WrapPanel` is included in the controls library @ https://github.com/wsick/fayde.controls.  Install the library by running `bower install fayde.controls` from your app root.  Then you can include your namespace in XAML, `xmlns:controls="lib://fayde.controls"`.

**Comment by deepaksm1** [comment]
Already done this. But nothing is appeared on page. Is there any extra steps or configuration I need to perform?

**Comment by BSick7** [comment]
What does your `fayde.json` file look like?

**Comment by deepaksm1** [comment]
Issue is resolved instead of lib://fayde.controls I was using lib://Fayde.Controls.
