### ISSUE TITLE
CheckBox rendering and Foreground

### ISSUE THREAD

**Issue by asthomas** [wsick/Fayde#98]
This checkbox code:
```xml
<Application
        xmlns="http://schemas.wsick.com/fayde"
        xmlns:x="http://schemas.wsick.com/fayde/x"
		xmlns:vsm="http://schemas.wsick.com/fayde"
        xmlns:vms="ViewModels"
        ThemeName="Metro">
  <Grid x:Name="LayoutRoot"
		HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
	<CheckBox Content="Hello" Foreground="Red"/>
  </Grid>
</Application>
```
Produces this in Fayde:
![image](https://cloud.githubusercontent.com/assets/2708028/7868609/64f3c730-054b-11e5-8cf2-5e7b4429337b.png)

And this in Silverlight:
![image](https://cloud.githubusercontent.com/assets/2708028/7868663/a17353ec-054b-11e5-8577-849b68025219.png)

The text content is not vertically centered, and the Foreground property is being ignored.

**Comment by BSick7** [comment]
The default styles for Fayde are similar to the Metro theme.  Any differences here could probably be attributed to the template.

**Comment by BSick7** [comment]
Modified style to be able to override CheckBox Foreground.
